from collections import deque

dq =deque()
dq.append(10)
dq.append(20)
dq.append(30)

print("Append 40 from left of deque")
dq.appendleft(40)
print(dq)
print("pop from 40 left of deque")
dq.popleft()
print(dq)
print("Pop 30 from right of deque")
dq.pop()
print(dq)
print("Insert 40 to 2nd index")
dq.insert(1,40)
print(dq)
print("Count items in deque")
print(dq.count(20))
print("Remove 20 from deque")
dq.remove(20)
print(dq)
print("Add 50,60 to right of deque")
dq.extend([50,60])
print(dq)
print("Add 70,80 to left of deque")
dq.extendleft([70,80])
print(dq)
print("Rotate elements clockwise in deque by 2")
dq.rotate(2)
print(dq)
print("Rotate elements anti-clockwise in deque by 4")
dq.rotate(-4)
print(dq)
print("Reverse deque elements")
dq.reverse()
print(dq)
print(dq[2])
